info:
  name: DELETE
  type: http
  seq: 5

http:
  method: DELETE
  url: "{{base_url}}/tasks/cmuy0qgsm000208nhjxn7l4ww"
  headers:
    - name: Authorization
      value: Bearer {{token}}
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        const result = await prisma.task.deleteMany({
          where: { id: taskId, userId: req.user.id },
        });

        if (result.count === 0) {
          return res.status(404).json({ error: "Tâche introuvable" });
        }

        return res.status(204).send();

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
