info:
  name: Find One Task
  type: http
  seq: 3

http:
  method: GET
  url: "{{base_url}}/tasks/{{taskId}}"
  headers:
    - name: Authorization
      value: Bearer {{token}}
  auth: inherit

runtime:
  variables:
    - name: taskId
      value: cmuyaz3xx000008o3eickkt9k
  scripts:
    - type: after-response
      code: bru.setEnvVar("taskId", res.getBody().id);
    - type: tests
      code: |-
        test("statut 200", function () {
          expect(res.getStatus()).to.equal(200);
        });

        test("id correspond", function () {
          expect(res.getBody().id).to.equal(bru.getEnvVar("taskId"));
        });

        test("appartient au bon utilisateur", function () {
          expect(res.getBody().userId).to.equal(bru.getEnvVar("userId"));
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
