version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/TaksAPiServer?schema=public
      - BETTER_AUTH_SECRET=B7BZme7EIJliZKYGZjhXVAcxUdTet+g6MswMy0oXIS4=
      - BETTER_AUTH_URL=http://localhost:3000
      - TRUSTED_ORIGINS=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TaksAPiServer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TaksAPiServer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: