name: Local
variables:
  - name: userId
    value: suIqasFoJ2XCUX5OWdm9aiMsqX8LzdrY
  - name: body
    value: ""
  - name: body1
    value: ""
  - name: token
    value: mTTg0adxnWOVICNvyBj3BOH4MnZBvK9j
  - name: taskId
    value: cmuyaz3xx000008o3eickkt9k
